--------------------------------------------------------
--  File created - Friday-February-02-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "SYS"."PAYMENT" 
   (	"ORDERID" NUMBER(*,0), 
	"USERID" NUMBER(10,0), 
	"CREDITCARD" NUMBER(20,0), 
	"SECURITYCODE" NUMBER, 
	"ZIPCODE" NUMBER, 
	"LOCATIONID" NUMBER(10,0), 
	"TOTALPAYMENT" NUMBER(10,2), 
	"ORDERDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.PAYMENT
SET DEFINE OFF;
Insert into SYS.PAYMENT (ORDERID,USERID,CREDITCARD,SECURITYCODE,ZIPCODE,LOCATIONID,TOTALPAYMENT,ORDERDATE) values (1,1,1111111111,123,11222,1,15,to_date('22-JAN-18','DD-MON-RR'));
Insert into SYS.PAYMENT (ORDERID,USERID,CREDITCARD,SECURITYCODE,ZIPCODE,LOCATIONID,TOTALPAYMENT,ORDERDATE) values (2,2,222222222,234,11222,1,12.5,to_date('23-JAN-18','DD-MON-RR'));
Insert into SYS.PAYMENT (ORDERID,USERID,CREDITCARD,SECURITYCODE,ZIPCODE,LOCATIONID,TOTALPAYMENT,ORDERDATE) values (3,2,3333333333,345,11222,2,14,to_date('24-JAN-18','DD-MON-RR'));
Insert into SYS.PAYMENT (ORDERID,USERID,CREDITCARD,SECURITYCODE,ZIPCODE,LOCATIONID,TOTALPAYMENT,ORDERDATE) values (4,3,4444444444,456,11222,2,30,to_date('26-JAN-18','DD-MON-RR'));
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "SYS"."PAYMENT" ADD CHECK (length(zipcode)>=5) DISABLE;
  ALTER TABLE "SYS"."PAYMENT" ADD CHECK (length(securityCode)>=3) DISABLE;
  ALTER TABLE "SYS"."PAYMENT" MODIFY ("ORDERDATE" NOT NULL DISABLE);
  ALTER TABLE "SYS"."PAYMENT" MODIFY ("ZIPCODE" NOT NULL DISABLE);
  ALTER TABLE "SYS"."PAYMENT" MODIFY ("SECURITYCODE" NOT NULL DISABLE);
  ALTER TABLE "SYS"."PAYMENT" MODIFY ("CREDITCARD" NOT NULL DISABLE);
  ALTER TABLE "SYS"."PAYMENT" MODIFY ("USERID" NOT NULL DISABLE);
