--------------------------------------------------------
--  File created - Friday-February-02-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_DATA
--------------------------------------------------------

  CREATE TABLE "SYS"."USER_DATA" 
   (	"ID" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"ZIPCODE" NUMBER, 
	"PHONE" NUMBER(10,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"ADMIN" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.USER_DATA
SET DEFINE OFF;
Insert into SYS.USER_DATA (ID,FIRSTNAME,LASTNAME,GENDER,ADDRESS,ZIPCODE,PHONE,EMAIL,PASSWORD,ADMIN) values (1,'William','Bigno','M','12345 Green St',11222,9291234,'wbigno@icloud.com','pass','1');
Insert into SYS.USER_DATA (ID,FIRSTNAME,LASTNAME,GENDER,ADDRESS,ZIPCODE,PHONE,EMAIL,PASSWORD,ADMIN) values (2,'Tommy','Smith','M','1234 East',11222,2133322,'tsmith@gmail.com','test','0');
Insert into SYS.USER_DATA (ID,FIRSTNAME,LASTNAME,GENDER,ADDRESS,ZIPCODE,PHONE,EMAIL,PASSWORD,ADMIN) values (3,'test','test','M','1234 Test Dr',12345,1231234,'test@test.com','pss','0');
--------------------------------------------------------
--  Constraints for Table USER_DATA
--------------------------------------------------------

  ALTER TABLE "SYS"."USER_DATA" ADD CHECK (length(zipcode)>=5) DISABLE;
  ALTER TABLE "SYS"."USER_DATA" ADD CHECK (gender in ('M','F,')) DISABLE;
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("EMAIL" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("PHONE" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("ZIPCODE" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("ADDRESS" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("GENDER" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("LASTNAME" NOT NULL DISABLE);
  ALTER TABLE "SYS"."USER_DATA" MODIFY ("FIRSTNAME" NOT NULL DISABLE);
